resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
- config.yaml
- rbac.yaml
- secret.yaml
commonLabels:
  app: omni-repository-server
  owner: tommylike
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: omni-repository
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/omni/omni-repository-test
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/omni/omni-repository-test
  newTag: 64780857a9aa632cb5fce27a8ca9e9e34b64693d
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
